version: '3'
services:
 client:
  image: busybox:latest
  tty: true
  container_name: client
  networks:
   net-10.9.0.0:
    ipv4_address: 10.9.0.5

 snort:
  build: .
  image: bibichannel/ubuntu:v2
  container_name: snort
  tty: true
  privileged: true
  networks:
   net-10.9.0.0:
    ipv4_address: 10.9.0.6

 server:
  image: nginx:latest
  container_name: web-server
  tty: true
  ports:
   - "80:80"
  networks:
   net-10.9.0.0:
    ipv4_address: 10.9.0.7
    
networks:
 net-10.9.0.0:
  name: net-10.9.0.0
  ipam:
   config:
    - subnet: 10.9.0.0/24
